### PR TITLE
Publish: Set the retain flag in the fixedheader

### LINKED ISSUE #37: Publish with retain doesn't retain
Publish works fine except for honoring the retain flag.  Broker works fine with external publishing with retain.
Using master branch: 460f0ef6815ae482f85dc3b0b7ca01d789f70ad6

```golang
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	mqtt "github.com/mochi-co/mqtt/server"
	"github.com/mochi-co/mqtt/server/listeners"
	"github.com/mochi-co/mqtt/server/listeners/auth"
)

func main() {
	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		done <- true
	}()

	server := mqtt.New()
	tcp := listeners.NewTCP("t1", ":1883")
	server.AddListener(tcp, &listeners.Config{Auth: new(auth.Allow)})

	// server.Serve doesn't block, so no need for goroutine, but for some
	// reason, we have to delay a LONG time for Serve's goroutines to start-up
	// > 1 second on a 5900X !!
	server.Serve()
	fmt.Println("\nServer is running")
	fmt.Println("Sleeping for 2 seconds")
	time.Sleep(2 * time.Second)

	// Publish with retain - doesn't work
	server.Publish("direct/publish", []byte("Published from broker"), true)
	fmt.Println("\nMessage published to \"direct/publish\" with retain")

	fmt.Println("\nTry running: mosquitto_sub -v -t \"direct/publish\"")

	<-done
}
```
```sh
go run main.go

# In another terminal window

# The following shows nothing
mosquitto_sub -v -t "direct/publish"

# But this works:
mosquitto_pub -t "mosquitto/publish" -m "from mosquitto_pub" -r
mosquitto_sub -v -t "mosquitto/publish"
```

Am I missing something?

### PR DESCRIPTION
**Pull request by stffabi**
Fixes #37

### CODE REVIEW

**Review by jmacd — APPROVED** [review]

File: server/server.go [hunk 1]
```diff
@@ -380,13 +380,14 @@ func (s *Server) Publish(topic string, payload []byte, retain bool) error {
 
 	pk := packets.Packet{
 		FixedHeader: packets.FixedHeader{
-			Type: packets.Publish,
+			Type:   packets.Publish,
```
Comment (mochi-co) [inline server/server.go:383]: Nicely caught!

**Review by mochi-co — APPROVED** [review]

**Comment by stffabi** [comment]
Awesome, thanks so much for merging.
